version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stoik-postgres
    restart: always
    environment:
      POSTGRES_USER: stoik_user
      POSTGRES_PASSWORD: stoik_password
      POSTGRES_DB: stoik_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
